// apps/next-app/app/components/bottomsheet/search/SearchSheet.tsx
'use client'
import React, { useState } from 'react'
import CoreSheet from '../core/CoreSheet'
import useSearchSheet from '@/store/useSearchSeet'
import useSearchData from '@/store/useSearchData'
import useUserLocationData from '@/store/useUserLocationData'
import HeaderSection from './partials/HeaderSection'
import SearchBox from '@/components/search/main/MainSearchBox'
import SearchResult from './partials/SearchResult'
import useEmergencyData from '@/store/useEmergencyData'
import NearestService from './partials/NearestService'
import InfoState from '@/components/commons/InfoState'
import { MapPin } from 'lucide-react'
import Tabs from '@/components/ui/Tabs'

const SearchSheet = () => {
    const { isOpen, snapPoint, onClose } = useSearchSheet()
    const { emergencyData } = useEmergencyData()
    const {
        searchResults,
        isLoading,
        isActive: isSearchBoxActive,
        setIsActive: setIsSearchBoxActive,
    } = useSearchData()
    const {
        fullAddress,
        updateFullAddress,
        updateCoordinate,
        updateRefetchMatrix,
    } = useUserLocationData()
    const [activeTab, setActiveTab] = useState(1)
    const snapPoints = [900, 280, 0]

    const tabs = [
        {
            value: 1,
            title: 'All',
        },
        {
            value: 2,
            title: 'Bantuan terdekat',
        },
    ]

    const handleSearchBoxFocus = () => {}
    const handleAddressSelect = (address: any) => {
        updateFullAddress(address.address)
        updateCoordinate(address.lat, address.long)
        updateRefetchMatrix() // refetch matrix on maps
        setIsSearchBoxActive(false) // set searchbox status to inactive
        onClose()
    }

    const handleNearestServiceSelect = (location: any) => {
        console.log(location)

        // updateFullAddress(location.address)
        // updateCoordinate(location.lat, location.long)
        // updateRefetchMatrix()
    }

    const filterEmergencyData = emergencyData?.filter((data: any) => {
        return data.responseTime.duration <= 10
    })

    const renderInfoState =
        !isSearchBoxActive && !isLoading && searchResults.length === 0
    const renderNearestService =
        searchResults.length === 0 &&
        !isLoading &&
        filterEmergencyData &&
        !isSearchBoxActive
    const renderNotFoundSearchButton =
        snapPoint === 1 && !isLoading && searchResults.length >= 1

    return (
        <div>
            <div className="bottom-sheet">
                <CoreSheet
                    isOpen={isOpen}
                    header={<HeaderSection />}
                    snapPoints={snapPoints}
                    initialSnap={0}
                    isOverlay
                    draggable={false}
                    scrollable={false}
                >
                    <div className="sheet-content h-full overflow-y-scroll">
                        <div className="heading sticky">
                            <div className="mb-2 px-3">
                                <SearchBox
                                    onFocus={handleSearchBoxFocus}
                                    onAddressSelect={handleAddressSelect}
                                    placeholder="Cari lokasi, desa atau daerah terdekat"
                                    showLocationButton={true}
                                />
                            </div>
                            <Tabs
                                tabs={tabs}
                                activeTab={activeTab}
                                setActiveTab={setActiveTab}
                                children={null}
                            />
                        </div>

                        <div className="content max-h-[80%] overflow-y-scroll">
                            <div className="all-tab-content">
                                {activeTab === 1 && (
                                    <>
                                        <div className="current-location my-3 px-3">
                                            {!isLoading && (
                                                <div className="flex items-center space-x-3 p-2 px-3 bg-blue-50 rounded-xl">
                                                    <div className="w-[10%]">
                                                        <div className="w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center">
                                                            <MapPin className="w-5 h-5 text-white" />
                                                        </div>
                                                    </div>
                                                    <div className="w-[85%]">
                                                        <h3 className="font-medium text-[15px] text-blue-600">
                                                            Lokasimu saat ini
                                                        </h3>
                                                        <div className="w-full">
                                                            <p className="text-[13.5px] text-blue-500 truncate">
                                                                {fullAddress ||
                                                                    'Lokasi tidak ditemukan'}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            )}
                                        </div>

                                        <div className="info-state">
                                            {renderInfoState && (
                                                <InfoState
                                                    size="xs"
                                                    title="Cari bantuan di sekitarmu"
                                                    description="Cari nama tempat, nama jalan, atau nama lokasi terdekatmu. Akan kami carikan bantuan"
                                                />
                                            )}
                                        </div>

                                        {/* Search Results Component */}
                                        {!isLoading && (
                                            <SearchResult
                                                locationResult={searchResults}
                                                handleSelectedAddress={
                                                    handleAddressSelect
                                                }
                                            />
                                        )}

                                        {/* Loading State */}
                                        {isLoading && (
                                            <div className="text-center py-8">
                                                <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
                                                <p className="text-sm text-gray-500">
                                                    Searching...
                                                </p>
                                            </div>
                                        )}

                                        {renderNotFoundSearchButton && (
                                            <div className="pb-8 px-3">
                                                <button className="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold text-md">
                                                    Lokasi tidak ditemukan? Cari
                                                    di Maps
                                                </button>
                                            </div>
                                        )}
                                    </>
                                )}
                            </div>
                            <div className="nearest-service-tab-content">
                                {activeTab === 2 && renderNearestService && (
                                    <div className="px-3 mt-3 bg-white mb-8 overflow-hidden">
                                        <NearestService
                                            emergency={filterEmergencyData}
                                            handleSelect={
                                                handleNearestServiceSelect
                                            }
                                        />
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </CoreSheet>
            </div>
        </div>
    )
}

export default SearchSheet

// apps/web-app/components/bottomsheet/SearchSheet.vue
<script setup lang="ts">
import { Icon } from "@iconify/vue";

const config = useRuntimeConfig();
const searchSheet = useSearchSheetStore();
const searchData = useSearchDataStore();
const userLocation = useUserLocationStore();
const leaflet = useLeafletStore();
const detailSheet = useDetailSheetStore();
const exploreSheet = useExploreSheetStore();
const { loadEmergencyData } = useEmergencyApi();

const query = ref("");
const results = ref<any[]>([]);
const loading = ref(false);
let searchTimer: ReturnType<typeof setTimeout> | null = null;

const hasQuery = computed(() => query.value.trim().length > 0);
const noResults = computed(() => !loading.value && results.value.length === 0 && hasQuery.value);

function handleSearch() {
  if (searchTimer) clearTimeout(searchTimer);
  if (!query.value.trim()) {
    results.value = [];
    return;
  }
  searchTimer = setTimeout(async () => {
    loading.value = true;
    try {
      const res = await $fetch<any>(
        `${config.public.apiBaseUrl}/api/v1/directions/geolocation?searchQuery=${encodeURIComponent(query.value)}`
      );
      results.value = res?.data?.features || [];
    } finally {
      loading.value = false;
    }
  }, 400);
}

async function handleSelect(item: any) {
  const lat = item.properties?.lat as number;
  const lng = item.properties?.lon as number;
  const address = item.properties?.formatted || item.properties?.name || "";

  userLocation.setManualLocation(true);
  userLocation.updateCoordinate(lat, lng);
  userLocation.updateFullAddress(address); // show Geoapify address immediately
  searchData.updateSearchCoordinate(lat, lng);
  leaflet.resetLeafletRouting();
  detailSheet.onClose();
  exploreSheet.onClose();

  searchSheet.onClose();
  query.value = "";
  results.value = [];

  await loadEmergencyData(lat, lng);
}

function handleSearchOnMaps() {
  searchSheet.onClose();
}

watch(query, (val) => {
  if (!val) results.value = [];
});
</script>

<template>
  <CoreSheet
    :is-open="searchSheet.isOpen"
    :snap-points="[500, 0]"
    is-overlay
    scrollable
    @close="searchSheet.onClose()"
  >
    <template #header>
      <div class="border-b py-3 px-3 bg-white border-neutral-100 rounded-t-[40px] flex items-center justify-between">
        <h1 class="text-md font-semibold text-neutral-800">Cari Lokasi</h1>
        <button
          class="bg-neutral-100 flex items-center justify-center w-8 h-8 rounded-full"
          @click="searchSheet.onClose()"
        >
          <Icon icon="ion:close" class="text-neutral-600 text-xl" />
        </button>
      </div>
    </template>

    <div class="h-full flex flex-col overflow-y-auto">
      <div class="sticky top-0 bg-white px-3 pt-3 pb-2 z-10">
        <div class="relative">
          <Icon icon="ph:magnifying-glass" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-lg" />
          <input
            v-model="query"
            type="text"
            placeholder="Cari lokasi, desa atau daerah terdekat"
            class="searchbox pl-9"
            @input="handleSearch"
          >
        </div>
      </div>

      <div class="flex-1 overflow-y-auto">
        <!-- Info state when empty -->
        <InfoState
          v-if="!loading && results.length === 0 && !hasQuery"
          size="xs"
          title="Cari bantuan di sekitarmu"
          description="Cari nama tempat, nama jalan, atau nama lokasi terdekatmu."
        />

        <!-- Loading skeleton -->
        <div v-if="loading" class="px-4 pt-3 space-y-3">
          <div v-for="i in 4" :key="i" class="flex items-start gap-3 animate-pulse">
            <div class="w-4 h-4 bg-gray-200 rounded-full mt-1 shrink-0" />
            <div class="flex-1 space-y-2">
              <div class="h-3 bg-gray-200 rounded w-3/4" />
              <div class="h-3 bg-gray-100 rounded w-1/2" />
            </div>
          </div>
        </div>

        <!-- Results -->
        <div v-if="!loading && results.length">
          <button
            v-for="(item, i) in results"
            :key="i"
            class="w-full px-4 py-3 text-left hover:bg-gray-50 border-b border-gray-100 flex items-start gap-3"
            @click="handleSelect(item)"
          >
            <Icon icon="mingcute:location-fill" class="text-red-500 mt-0.5 shrink-0" />
            <span class="text-sm text-gray-700 leading-snug">{{ item.properties?.formatted }}</span>
          </button>
        </div>

        <!-- No results CTA -->
        <div v-if="noResults" class="px-4 py-8 text-center">
          <Icon icon="mingcute:search-line" class="text-gray-300 text-4xl mx-auto mb-3" />
          <p class="text-sm text-gray-500 mb-6">
            Lokasi "<span class="font-medium text-gray-700">{{ query }}</span>" tidak ditemukan.
          </p>
          <div class="flex flex-col gap-2">
            <button type="button" class="btn-dark" @click="handleSearchOnMaps">
              <Icon icon="mingcute:map-2-line" class="mr-2" />
              Cari alamat di maps
            </button>
            <button type="button" class="btn-base hover:bg-neutral-100" @click="searchSheet.onClose()">
              Tutup
            </button>
          </div>
        </div>
      </div>
    </div>
  </CoreSheet>
</template>
