// apps/next-app/app/components/menu/BottomMenu.tsx
'use client'
import React from 'react'
import { useEmergencyTypeApi } from '@/store/api/emergency-type.api'
import PreviewSearchBox from '../search/preview/PreviewSearchBox'
import useExploreSheet from '@/store/useExploreSheet'
import AvailableServiceList from './AvailableServiceList'
import { filterEmergencyByService } from '@/utils/filterEmergencyByService'

const BottomMenu = () => {
    const { emergencyTypeData, emergencyTypeLoading } = useEmergencyTypeApi()
    const { setSheetData: setExploreSheetData, onOpen: openExploreSheet } =
        useExploreSheet()

    const handleServiceClick = async (service?: any) => {
        const serviceName = service?.name
        const filteredEmergencyByService = filterEmergencyByService(serviceName)
        setExploreSheetData({
            emergencyType: service,
            emergency: filteredEmergencyByService,
        })
        openExploreSheet()
    }

    const skeletonLoader = () => {
        return (
            <div className="w-24 flex flex-col items-center space-y-2 animate-pulse">
                <div className="w-[50px] h-[50px] bg-red-100 rounded-full flex items-center justify-center">
                    <div className="w-7 h-7 bg-red-300 rounded-md"></div>
                </div>

                <div className="w-16 h-3 bg-gray-300 rounded"></div>
            </div>
        )
    }

    return (
        <div
            data-testid="bottom-menu"
            className="sticky bottom-0 left-0 z-50 w-full h-[100%] py-5 rounded-t-xl bg-white border-t-slate-200 bottom-menu-shadow"
        >
            <div className="sheet-wrapper">
                <div className="sheet-header mx-4">
                    <PreviewSearchBox />
                </div>
                <div className="sheet-body mt-4">
                    {emergencyTypeLoading && (
                        <div className="grid grid-cols-4 mt-2">
                            <div>{skeletonLoader()}</div>
                            <div>{skeletonLoader()}</div>
                            <div>{skeletonLoader()}</div>
                            <div>{skeletonLoader()}</div>
                        </div>
                    )}

                    <AvailableServiceList
                        emergencyTypeData={emergencyTypeData}
                        handleServiceClick={handleServiceClick}
                    />
                </div>
            </div>
        </div>
    )
}

export default BottomMenu

// apps/web-app/components/menu/BottomMenu.vue
<script setup lang="ts">
const exploreSheet = useExploreSheetStore();
const emergencyStore = useEmergencyStore();

const { fetchEmergencyTypes } = useEmergencyApi();
const { data: emergencyTypeData, pending: loading } = useAsyncData(
  "emergency-types",
  fetchEmergencyTypes
);

function handleServiceClick(service: any) {
  const filtered = emergencyStore.filteredEmergency.filter(
    (item: any) => item.emergencyData?.emergency_type?.name === service.name
  );
  exploreSheet.setSheetData({ emergencyType: service, emergency: filtered });
  exploreSheet.onOpen();
}
</script>

<template>
  <div
    class="sticky bottom-0 left-0 z-50 w-full h-full py-5 rounded-t-xl bg-white border-t border-slate-200 bottom-menu-shadow"
  >
    <div class="sheet-header mx-4 flex items-center gap-3">
      <div class="flex-1 min-w-0 overflow-hidden">
        <PreviewSearchBox />
      </div>
      <SosButton />
    </div>
    <div class="sheet-body mt-4">
      <AvailableServiceList
        :emergency-type-data="emergencyTypeData"
        :loading="loading"
        @service-click="handleServiceClick"
      />
    </div>
  </div>
</template>
