// apps/next-app/app/components/commons/EmptyState.tsx
import React from 'react'
import { Plus } from 'lucide-react'
import Image from 'next/image'

type Props = {
    title: string
    size: 'xxs' | 'xs' | 'sm' | 'md'
    description?: string
    cta?: React.ReactNode
}

const imageSizeClasses = {
    xxs: 100,
    xs: 130,
    sm: 180,
    md: 300,
}

const EmptyState: React.FC<Props> = ({ title, description, cta, size }) => {
    return (
        <div className=" bg-white flex items-center justify-center px-8 py-3">
            <div className="text-center max-w-md">
                {/* File Folder Illustration */}
                <div className="mb-3 relative flex items-center justify-center">
                    <Image
                        src="/assets/illustration/core/data-not-found-2.svg"
                        alt="File Folder Illustration"
                        width={imageSizeClasses[size]}
                        height={imageSizeClasses[size]}
                    />
                </div>

                {/* Heading */}
                <h2 className={`text-lg font-semibold text-gray-900 mb-1`}>
                    {title}
                </h2>

                {/* Description */}
                <p className="text-gray-600 text-[15px] mb-3">{description}</p>

                {/* Action Button */}
                <div>{cta}</div>
            </div>
        </div>
    )
}

export default EmptyState

// apps/web-app/components/commons/EmptyState.vue
<script setup lang="ts">
const sizeMap = { xxs: "w-24", xs: "w-32", sm: "w-44", md: "w-72" };
defineProps<{
  title: string;
  size?: "xxs" | "xs" | "sm" | "md";
  description?: string;
}>();
</script>

<template>
  <div class="bg-white flex items-center justify-center px-8 py-3">
    <div class="text-center max-w-md">
      <div class="mb-3 flex items-center justify-center">
        <img
          src="/assets/illustration/core/data-not-found-2.svg"
          alt="Tidak ditemukan"
          :class="sizeMap[size ?? 'xs']"
        />
      </div>
      <h2 class="text-lg font-semibold text-gray-900 mb-1">{{ title }}</h2>
      <p v-if="description" class="text-gray-600 text-[15px] mb-3">{{ description }}</p>
      <slot />
    </div>
  </div>
</template>
